apiVersion: v1
kind: PersistentVolume 
metadata:
  name: ebs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi: 
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-09c7b5f507cb9cdf7