apiVersion: v1 
kind: pod 
metadata: 
  name: annotations
  labels:
    project: roboshop
    component: frontend
    environment: Dev
  annotations:
    imageregistry: "https://hub.docker.com"
    jenkinsURL: "https://jenkins.joindevops.com/build/roboshop/34"
spec:
  - name: nginx
    image: nginx